export type TopModuleId = 'monitoring' | 'intelligent' | 'video' | 'four-tables' | 'water' | 'electricity' | 'explosives' | 'sms' | 'personnel' | 'mining' | 'basic' | 'system';

export interface TopModule {
  id: TopModuleId;
  label: string;
}

export interface MenuItem {
  id: string;
  label: string;
  page: string;
  icon?: string;
  children?: MenuItem[];
}

export const topModules: TopModule[] = [
  { id: 'monitoring', label: '监测预警' },
  { id: 'intelligent', label: '矿数卫士' },
  { id: 'video', label: '视频集中管理平台' },
  { id: 'four-tables', label: '矿压监测' },
  { id: 'water', label: '露天煤矿管理' },
  { id: 'electricity', label: '从业人员管理' },
  { id: 'explosives', label: '采掘通' },
  { id: 'sms', label: '短信管理' },
  { id: 'basic', label: '基本信息' },
  { id: 'system', label: '系统管理' },
];

export const menuGroups: Record<TopModuleId, MenuItem[]> = {
  monitoring: [
    { id: 'alarm-disposal', label: '报警处置', page: 'alarm-disposal', icon: 'gear' },
    { id: 'data-query', label: '数据查询', page: 'monitor-alarm-query', icon: 'search', children: [
      { id: 'monitor-alarm-query', label: '报警查询', page: 'monitor-alarm-query' },
      { id: 'monitor-disposal-record', label: '处置记录', page: 'monitor-disposal-record' },
      { id: 'monitor-methane-record', label: '甲烷超限处置记录', page: 'monitor-methane-record' },
    ] },
    { id: 'warning-manage', label: '预警管理', page: 'monitor-warning-query', icon: 'alarm', children: [
      { id: 'monitor-warning-query', label: '预警查询', page: 'monitor-warning-query' },
      { id: 'monitor-warning-rule', label: '预警规则设置', page: 'monitor-warning-rule' },
    ] },
    { id: 'record-fix', label: '处置记录修正管理', page: 'monitor-record-fix', icon: 'list' },
    { id: 'env-monitor', label: '环境监测监控', page: 'monitor-env-monitor', icon: 'gauge' },
    { id: 'person-track', label: '人员轨迹历史查询', page: 'monitor-person-track', icon: 'clock' },
    { id: 'shift-query', label: '交接班查询', page: 'monitor-shift-record-query', icon: 'users', children: [
      { id: 'monitor-shift-record-query', label: '交接班记录查询', page: 'monitor-shift-record-query' },
      { id: 'monitor-enterprise-shift-record', label: '企业交接班记录', page: 'monitor-enterprise-shift-record' },
    ] },
    { id: 'monitor-sms', label: '短信管理', page: 'monitor-sms-record', icon: 'mail', children: [
      { id: 'monitor-sms-record', label: '短信发送记录查询', page: 'monitor-sms-record' },
      { id: 'monitor-sms-rule', label: '短信发送规则设置', page: 'monitor-sms-rule' },
      { id: 'monitor-sms-government-receiver', label: '政府接收人员', page: 'monitor-sms-government-receiver' },
      { id: 'monitor-sms-enterprise-receiver', label: '企业接收人员', page: 'monitor-sms-enterprise-receiver' },
      { id: 'monitor-sms-template', label: '短信内容模板设置', page: 'monitor-sms-template' },
    ] },
    { id: 'shift-setting', label: '班次设置', page: 'monitor-shift-setting', icon: 'calendar' },
    { id: 'alarm-rule', label: '报警提示规则设置', page: 'monitor-alarm-rule', icon: 'alert' },
    { id: 'sensor-log', label: '传感器变更日志', page: 'monitor-sensor-log', icon: 'briefcase' },
    { id: 'leader-duty', label: '矿领导带班', page: 'monitor-leader-plan', icon: 'user', children: [
      { id: 'monitor-leader-plan', label: '带班计划', page: 'monitor-leader-plan' },
      { id: 'monitor-leader-completion', label: '带班计划完成情况', page: 'monitor-leader-completion' },
      { id: 'monitor-downhole-record', label: '下井带班记录', page: 'monitor-downhole-record' },
    ] },
    { id: 'report-manage', label: '报备管理', page: 'monitor-report-audit', icon: 'file', children: [
      { id: 'monitor-report-audit', label: '报备审核', page: 'monitor-report-audit' },
      { id: 'monitor-report-query', label: '报备查询', page: 'monitor-report-query' },
    ] },
    { id: 'report-statistics', label: '报备统计', page: 'monitor-report-statistics', icon: 'chart' },
    { id: 'statistics', label: '统计分析', page: 'monitor-network-statistics', icon: 'chart', children: [
      { id: 'monitor-network-statistics', label: '联网统计', page: 'monitor-network-statistics' },
      { id: 'monitor-alarm-statistics', label: '报警处置统计', page: 'monitor-alarm-statistics' },
      { id: 'monitor-alarm-ranking', label: '报警排行榜', page: 'monitor-alarm-ranking' },
      { id: 'monitor-person-history-statistics', label: '人员历史数据统计', page: 'monitor-person-history-statistics' },
      { id: 'monitor-person-location-statistics', label: '人员定位统计', page: 'monitor-person-location-statistics' },
      { id: 'monitor-comprehensive-report', label: '综合报告分析', page: 'monitor-comprehensive-report' },
      { id: 'monitor-disconnect-statistics', label: '断线统计', page: 'monitor-disconnect-statistics' },
      { id: 'monitor-duty-vacancy-statistics', label: '带班空岗统计', page: 'monitor-duty-vacancy-statistics' },
      { id: 'monitor-key-sensor-ranking', label: '重点传感器排行榜', page: 'monitor-key-sensor-ranking' },
      { id: 'monitor-sensor-count-statistics', label: '传感器数量统计', page: 'monitor-sensor-count-statistics' },
    ] },
    { id: 'workgroup', label: '煤矿监管工作组管理', page: 'monitor-workgroup', icon: 'idcard', children: [
      { id: 'monitor-regulatory-list', label: '监管名单', page: 'monitor-regulatory-list' },
      { id: 'monitor-downhole-statistics', label: '下井记录统计', page: 'monitor-downhole-statistics' },
    ] },
  ],
  sms: [
    { id: 'sms-record', label: '短信发送记录查询', page: 'sms-record', icon: 'mail' },
    { id: 'sms-rule', label: '短信发送规则设置', page: 'sms-rule', icon: 'settings' },
    { id: 'sms-enterprise-receiver', label: '企业接收人员', page: 'sms-enterprise-receiver', icon: 'briefcase' },
    { id: 'sms-government-receiver', label: '政府接收人员', page: 'sms-government-receiver', icon: 'home' },
    { id: 'sms-other-unit-address-book', label: '其他单位通讯录', page: 'sms-other-unit-address-book', icon: 'users' },
    { id: 'sms-template', label: '短信内容模板设置', page: 'sms-template', icon: 'file' },
  ],
  basic: [
    { id: 'company-basic', label: '企业基本信息', page: 'placeholder-company-basic', icon: 'file', children: [
      { id: 'enterprise-archive', label: '企业档案查询', page: 'enterprise-archive' },
      { id: 'enterprise-license-warning', label: '企业证照预警', page: 'placeholder-enterprise-license-warning' },
      { id: 'special-license-warning', label: '企业特殊作业证照预警', page: 'placeholder-special-license-warning' },
    ] },
    { id: 'basic-statistics', label: '统计分析', page: 'placeholder-basic-statistics', icon: 'pie', children: [] },
  ],
  video: [
    { id: 'video-dashboard', label: '数据总览', page: 'placeholder-video-dashboard', icon: 'monitor' },
    { id: 'video-carousel', label: '视频轮播', page: 'placeholder-video-carousel', icon: 'video', children: [] },
    { id: 'coal-video-query', label: '煤矿视频查询', page: 'placeholder-coal-video-query', icon: 'image' },
    { id: 'video-change-list', label: '视频变更清单', page: 'video-detail', icon: 'clipboard' },
    { id: 'video-realtime', label: '视频实时状态统计', page: 'placeholder-video-realtime', icon: 'timer' },
    { id: 'video-category', label: '视频分类统计', page: 'placeholder-video-category', icon: 'bar' },
    { id: 'decoder', label: '解码器管理', page: 'placeholder-decoder', icon: 'text' },
    { id: 'video-account', label: '视频台账管理', page: 'placeholder-video-account', icon: 'folder' },
    { id: 'app-video', label: 'App视频查看管理', page: 'placeholder-app-video', icon: 'app' },
    { id: 'video-warning', label: '预警管理', page: 'placeholder-video-warning', icon: 'bell', children: [] },
    { id: 'play-setting', label: '播放设置', page: 'placeholder-play-setting', icon: 'settings' },
  ],
  system: [
    { id: 'system-organization', label: '组织机构', page: 'system-organization', icon: 'home' },
    { id: 'system-personnel', label: '系统人员', page: 'system-personnel', icon: 'user' },
    { id: 'system-role-auth', label: '角色授权', page: 'placeholder-system-role-auth', icon: 'idcard' },
    { id: 'system-user', label: '系统用户', page: 'system-user', icon: 'users' },
    { id: 'system-data-permission', label: '数据权限设置', page: 'placeholder-system-data-permission', icon: 'gear' },
    { id: 'system-password-reset', label: '密码重置', page: 'placeholder-system-password-reset', icon: 'lock' },
  ],
  intelligent: [
    { id: 'guard-data-panel', label: '数据面板', page: 'guard-home', icon: 'monitor', children: [
      { id: 'guard-home', label: '首页', page: 'guard-home' },
      { id: 'guard-gas-emission-abnormal', label: '瓦斯涌出异常', page: 'guard-gas-emission-abnormal' },
      { id: 'guard-carbon-monoxide-abnormal', label: '一氧化碳变化异常', page: 'guard-carbon-monoxide-abnormal' },
      { id: 'guard-pipeline-flow-abnormal', label: '管道流量变化异常', page: 'guard-pipeline-flow-abnormal' },
      { id: 'guard-pipeline-pressure-abnormal', label: '管道压力变化异常', page: 'guard-pipeline-pressure-abnormal' },
      { id: 'guard-methane-change-abnormal', label: '瓦斯变化异常', page: 'guard-methane-change-abnormal' },
      { id: 'guard-methane-constant-abnormal', label: '瓦斯恒值异常', page: 'guard-methane-constant-abnormal' },
      { id: 'guard-stop-group-abnormal', label: '开停组停运异常', page: 'guard-stop-group-abnormal' },
      { id: 'guard-lock-cycle-abnormal', label: '闭锁周期异常', page: 'guard-lock-cycle-abnormal' },
      { id: 'guard-downhole-count-abnormal', label: '人员下井次数不达标', page: 'guard-downhole-count-abnormal' },
      { id: 'guard-leader-handover-abnormal', label: '带班领导交接班异常', page: 'guard-leader-handover-abnormal' },
      { id: 'guard-downhole-inspection-abnormal', label: '人员下井巡检异常', page: 'guard-downhole-inspection-abnormal' },
      { id: 'guard-video-offline', label: '视频断线', page: 'guard-video-offline' },
      { id: 'guard-overlimit-no-alarm', label: '超限未报警', page: 'guard-overlimit-no-alarm' },
    ] },
    { id: 'guard-assist-setting', label: '辅助设置', page: 'guard-report-export', icon: 'settings', children: [
      { id: 'guard-report-export', label: '报表导出', page: 'guard-report-export' },
      { id: 'guard-gas-emission-search', label: '瓦斯涌出量查询', page: 'guard-gas-emission-search' },
      { id: 'guard-workface-query', label: '工作面查询', page: 'guard-workface-query' },
      { id: 'guard-log-query', label: '操作日志查询', page: 'guard-log-query' },
      { id: 'guard-log-router', label: '操作日志路由配置', page: 'guard-log-router' },
      { id: 'guard-gas-dispose', label: '处置管理', page: 'guard-gas-dispose' },
      { id: 'guard-outburst-point', label: '涌出点管理', page: 'guard-outburst-point' },
      { id: 'guard-rule-approval', label: '煤矿规则审批', page: 'guard-rule-approval' },
      { id: 'guard-safe-risk-report', label: '安全风险研判报告', page: 'guard-safe-risk-report' },
    ] },
    { id: 'guard-sms-management', label: '短信管理', page: 'placeholder-guard-sms-management', icon: 'mail' },
    { id: 'guard-system-management', label: '系统管理', page: 'placeholder-guard-system-management', icon: 'gear' },
    { id: 'guard-hidden-risk', label: '隐蔽面风险综合分析', page: 'guard-hidden-risk-overview', icon: 'alarm', children: [
      { id: 'guard-hidden-risk-overview', label: '风险总览一张图', page: 'guard-hidden-risk-overview' },
      { id: 'guard-hidden-risk-mine-profile', label: '煤矿风险画像', page: 'guard-hidden-risk-mine-profile' },
      { id: 'guard-hidden-risk-clue-ledger', label: '线索证据台账', page: 'guard-hidden-risk-clue-ledger' },
      { id: 'guard-hidden-risk-task', label: '工作安排处置', page: 'guard-hidden-risk-task' },
      { id: 'guard-hidden-risk-config', label: '配置管理', page: 'guard-hidden-risk-config' },
    ] },
  ], 'four-tables': [], water: [], electricity: [], explosives: [], personnel: [], mining: [],
};

export const pageToModule: Record<string, TopModuleId> = {

  'guard-home': 'intelligent',
  'guard-gas-emission-abnormal': 'intelligent',
  'guard-carbon-monoxide-abnormal': 'intelligent',
  'guard-pipeline-flow-abnormal': 'intelligent',
  'guard-pipeline-pressure-abnormal': 'intelligent',
  'guard-methane-change-abnormal': 'intelligent',
  'guard-methane-constant-abnormal': 'intelligent',
  'guard-stop-group-abnormal': 'intelligent',
  'guard-lock-cycle-abnormal': 'intelligent',
  'guard-downhole-count-abnormal': 'intelligent',
  'guard-leader-handover-abnormal': 'intelligent',
  'guard-downhole-inspection-abnormal': 'intelligent',
  'guard-video-offline': 'intelligent',
  'guard-overlimit-no-alarm': 'intelligent',
  'guard-report-export': 'intelligent',
  'guard-gas-emission-search': 'intelligent',
  'guard-workface-query': 'intelligent',
  'guard-log-query': 'intelligent',
  'guard-log-router': 'intelligent',
  'guard-gas-dispose': 'intelligent',
  'guard-outburst-point': 'intelligent',
  'guard-rule-approval': 'intelligent',
  'guard-safe-risk-report': 'intelligent',
  'guard-hidden-risk-overview': 'intelligent',
  'guard-hidden-risk-mine-profile': 'intelligent',
  'guard-hidden-risk-clue-ledger': 'intelligent',
  'guard-hidden-risk-task': 'intelligent',
  'guard-hidden-risk-config': 'intelligent',
  'alarm-disposal': 'monitoring',
  'monitor-alarm-query': 'monitoring',
  'monitor-disposal-record': 'monitoring',
  'monitor-methane-record': 'monitoring',
  'monitor-warning-query': 'monitoring',
  'monitor-warning-rule': 'monitoring',
  'monitor-record-fix': 'monitoring',
  'monitor-env-monitor': 'monitoring',
  'monitor-person-track': 'monitoring',
  'monitor-shift-record-query': 'monitoring',
  'monitor-enterprise-shift-record': 'monitoring',
  'monitor-sms-record': 'monitoring',
  'monitor-sms-rule': 'monitoring',
  'monitor-sms-government-receiver': 'monitoring',
  'monitor-sms-enterprise-receiver': 'monitoring',
  'monitor-sms-template': 'monitoring',
  'monitor-shift-setting': 'monitoring',
  'monitor-alarm-rule': 'monitoring',
  'monitor-sensor-log': 'monitoring',
  'monitor-leader-plan': 'monitoring',
  'monitor-leader-completion': 'monitoring',
  'monitor-downhole-record': 'monitoring',
  'monitor-report-audit': 'monitoring',
  'monitor-report-query': 'monitoring',
  'monitor-report-statistics': 'monitoring',
  'monitor-network-statistics': 'monitoring',
  'monitor-alarm-statistics': 'monitoring',
  'monitor-alarm-ranking': 'monitoring',
  'monitor-person-history-statistics': 'monitoring',
  'monitor-person-location-statistics': 'monitoring',
  'monitor-comprehensive-report': 'monitoring',
  'monitor-disconnect-statistics': 'monitoring',
  'monitor-duty-vacancy-statistics': 'monitoring',
  'monitor-key-sensor-ranking': 'monitoring',
  'monitor-sensor-count-statistics': 'monitoring',
  'monitor-workgroup': 'monitoring',
  'monitor-regulatory-list': 'monitoring',
  'monitor-downhole-statistics': 'monitoring',
  'enterprise-archive': 'basic',
  'video-detail': 'video',
  'sms-record': 'sms',
  'sms-rule': 'sms',
  'sms-enterprise-receiver': 'sms',
  'sms-government-receiver': 'sms',
  'sms-other-unit-address-book': 'sms',
  'sms-template': 'sms',
  'system-organization': 'system',
  'system-personnel': 'system',
  'system-user': 'system',
};

